client/components/sandbox.js, client/routes.js, package-lock.json, package.json
- created code sandbox on route /sandbox
- function name and args are pulled from dummy data object
- gives success/failure/error(?) back based on dummy data input/output arrays
=> Code editor

client/components/sandbox.js
closes #3
- added descriptive message for when a function fails
=> added descriptive message when a users function failes

client/components/game-stage.js, client/components/home-stage.js, client/components/index.js, client/components/sandbox.js, client/components/stage-info.js, client/components/user-home.js, client/routes.js, client/store/index.js, client/store/localStorage.js, client/store/sessionStorage.js, client/store/stage.js, package-lock.json, package.json, script/seed.js, script/stageData.js, server/api/stages.js, server/api/users.js, server/api/users.spec.js, server/auth/index.js, server/db/models/stage.js, server/db/models/user.js
**upon pull origin and merge:**
1. reseed your local db
2. run npm i to install new dependencies from this pull (lodash)
3. createdb ratquest-test to run tests
---
**React components to display user stage progress:**
- stage-info: higher order component that wraps home-stage and game-stage; retrieves info from store/thunk that makes api call to api users stages endpoint; want to reuse logic on two unique presentational components, home-stage and game-stage
- home-stage: stage info to be displayed on home page; possibly that will display more than one of these on home page with only currently played stage activated
- game-stage: stage info, how far into stage problems, for game-play page where sandbox editor will be located
close #20
=> Home react setup

server/db/models/index.js, server/db/models/user.js
add model/association changes for user and problem
---
=> Material design

client/components/home-stage.js, client/components/sandbox.js, client/components/stage-info.js, client/store/problem.js, script/seed.js, server/api/problems.js, server/db/models/problem.js
can fetch a random problem from the list of problems that are not solved for the stage and "active".
the play button on the home stage works as well.
you need to run seed after merge!
---
=> can fetch a random problem from the list of problems that are not solved for the stage and "active"

client/components/Admin.js, server/api/users.js
=> add problems to admin

client/components/navbar.js
Fixed nav so admin link available if logged in as admin
=> Working on admin

server/api/problems.js
=> minor fix on new user sandbox

client/components/multiplayer.js, client/components/multiplayerHome.js, client/components/sandbox.js, client/routes.js, client/store/user.js, script/gameData.js, script/seed.js, server/api/index.js, server/api/multiplayer.js, server/api/users.js, server/auth/index.js, server/db/models/game.js, server/db/models/index.js, server/socket/index.js
=> Multiplayer3

client/components/multiplayer.js, server/api/multiplayer.js, server/auth/index.js, server/socket/index.js
- got rid of socket disconnect
=> fixed socket disconnect

client/components/sandbox.js
=> added cheat button

script/problemData.js, server/api/problems.js, server/db/models/problem.js
=> Updated seed data for problems

client/components/multiplayer.js, client/components/multiplayerHome.js, client/components/sandbox.js, client/routes.js, client/socket.js, server/api/problems.js, server/socket/index.js
- fixed res.end()
- finished multiplayer functionality, need to work on styling
=> Multiplayer7

client/components/game-stage.js, client/components/rat.js, client/components/sandbox-rat.js, client/components/sandbox.js, client/components/user-home.js, client/store/index.js, client/store/user.js, package-lock.json, package.json, public/style.css
=> Sandbox style

.babelrc, .d.ts, client/components/board.js, client/components/rat.js, client/components/sandbox-rat.js, webpack.config.js
=> Testing settings re travis

client/components/sandbox.js
=> Minorstage

webpack.config.js
=> fixed fd error

client/components/board.js, client/store/index.js, client/store/user.js
=> Store unsubscribe

client/components/multiplayer.js, client/components/multiplayerHome.js, client/lobbySocket.js, client/socket.js, public/style.css
- styled lobby home screen
- created separate lobby emit
=> Multiplayerstyle

client/components/auth-form.js, client/components/rat.js, public/style.css
=> fixed bug rat component did mount (ghost rat) and signup -login bug

client/components/music.js, client/components/navbar.js
Added background music with play/pause button on nav bar
---
=> Added background music with play/pause button on nav bar

client/components/Admin.js, client/components/multiplayer.js, client/components/multiplayerHome.js, client/components/sandbox.js, public/style.css
*[ ] added padding where needed
=> quick padding and cheat button implemented

client/components/user-home.js
=> fixed load bug
